service: AqlRequest

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: java8
  stage: dev # Set the default stage used. Default is dev
  region: ${opt:stage, 'eu-west-1'} # Overwrite the default region used. Default is us-east-1
  profile: PERSO # The default profile to use with this service
  memorySize: 512 # Overwrite the default memory size. Default is 1024
  timeout: 30
  iamRoleStatements: # permissions for all of your functions can be set here
    - Effect: Allow
      Action: # Gives permission to DynamoDB tables in a specific region
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:DescribeStream
        - dynamodb:GetRecords
        - dynamodb:GetShardIterator
        - dynamodb:ListStreams
      Resource:
        Fn::GetAtt: [ usersTable , Arn ]
  
package:
  artifact: target/aql-request.jar

functions:
  currentTime:
    handler: com.aql.request.Handler
    environment:
      REGION: ${self:provider.region}
      TABLE_NAME: aqlRequest
    events:
      - http:
          path: request
          method: post
  indexAqlRequest:
    handler: com.aql.request.HandlerIndex
    environment:
      REGION: ${self:provider.region}
      ELASTICSEARCH_ENDPOINT:
        Fn::GetAtt: [ ElasticSearchCluster , DomainEndpoint ]
    events:
      - stream: 
          type: dynamodb
          arn:
            Fn::GetAtt:
              - usersTable
              - StreamArn

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: "aqlRequest"
        AttributeDefinitions:
          - AttributeName: "email"
            AttributeType: "S"
          - AttributeName: "timestamp"
            AttributeType: "N"
        KeySchema:
          - AttributeName: "timestamp"
            KeyType: "HASH"
          - AttributeName: "email"
            KeyType: "RANGE"
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        StreamSpecification:
          StreamViewType: NEW_IMAGE
    ElasticSearchCluster:
      Type: AWS::Elasticsearch::Domain
      Properties:
        DomainName: aql
        EBSOptions:
          EBSEnabled: true
          VolumeType: gp2
          VolumeSize: 10
        ElasticsearchClusterConfig:
          InstanceType: t2.small.elasticsearch
          InstanceCount: 1
          DedicatedMasterEnabled: false
          ZoneAwarenessEnabled: false
        ElasticsearchVersion: 5.3
        AccessPolicies:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - es:*
              Resource: arn:aws:es:eu-west-1:999566048748:domain/aql/*
              Principal:
                AWS: 
                  - arn:aws:iam::999566048748:role/AqlRequest-dev-eu-west-1-lambdaRole
                  - arn:aws:iam::999566048748:user/AqlKibanaAdmin